config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  # Home
  root "posts#index"

  # About
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5 }
  validates :body, presence: true

  belongs_to :user, optional: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @comment = current_user.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save

    if @comment.save
      redirect_to post_path(@post)
    else
      redirect_to root_path
    end

  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

        def comment_params
            params.require(:comment).permit(:name, :body)
        end

        def find_comment
            @post = Post.find(params[:post_id])
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    @post.save
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><strong><%= comment.body %></strong></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at )%> Ago</p>
  </div>
  <% if @post.user == current_user && user_signed_in? %>
  <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: {confirm: 'Are you sure?'} %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <br />
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogdog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
        <%= image_tag "blogdog.png" %>
      <% end %>
    </div>

    <ul>
      <li class="category" style="font-size: 12px; text-align: right;">BlogDog</li>
      <li><%= link_to "Top Dogs", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://www.linkedin.com/in/bikeda/" target="_blank">LinkedIn</a></li>
      <li><a href="https://github.com/xikeda" target="_blank">Github</a></li>
      <li><a href="mailto:brandon.k.ikeda@gmail.com">Email</a></li>
    </ul>
  </div>

  <div id="main_content">
    <div id="header">
      <% if !user_signed_in? %>
      <div class="buttons">
        <button class="button" style="padding-left: 2.5em;"><a href="/users/sign_in">Log in</a></button>
        <button class="button" style="padding-left: 2.5em;"><a href="/users/sign_up">Sign up</a></button>
      </div>
      <% end %>

      <% if user_signed_in? %>
      <div class="buttons">
        <button class="button" style="padding-left: 2.5em;"><%= link_to "Bark", new_post_path %></button>
        <button class="button" style="padding-left: 2.5em;"> <%= link_to('Logout', destroy_user_session_path, method: :delete) %> </button>
      </div>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "yoyo2.jpeg" %>
  </div>

  <div id="content">
    <h2>Hey, I'm Brandon Ikeda</h2>
    <h3>When I'm not making the web, I'm making waves</h3>
    <p>Full-stack Developer specializing in back-end and front end development with 3+ years experience. Experienced with all stages of the development cycle for web projects. Well-versed in Java, C/C++, Python, PHP, Ruby including frameworks like Rails, TDD using Rspec, Github, Javascript including frameworks like JQuery, AngularJS and React, Postgresql, MongoDB, Heroku, Bootstrap and HTML/CSS. I am passionate about technology, law and the great outdoors!</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any?%>
    <div id="errors">
      <h5><%= pluralize(@post.errors.count, "error")%> prevented this post from saving:</h5>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <br />
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= f.label :title%><br>
  <%= f.text_field :title%>
  </p

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

</p>
    <%= f.submit :Bark! %>
  </p>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h3> Edit Bark </h3><br />

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h4 class="title"><%= link_to post.title, post %></h4>
    <p class="date">Barked on <%= post.created_at.strftime("%B, %d, %Y") %></p>

      <div class="btn-group">
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm", style: "color: green;"  do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Good Dog
        <%= post.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm", style: "color: red;" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        Bad Dog
        <%= post.get_downvotes.size %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h3> New Bark </h3><br />

  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any?%>
      <div id="errors">
        <h5><%= pluralize(@post.errors.count, "error")%> prevented this post from saving:</h5>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <br />
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
    <%= f.label :title%><br>
    <%= f.text_field :title%>
    </p

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

  </p>
      <%= f.submit :Bark! %>
    </p>

  <% end %>

</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h3 class="title">
    <%= @post.title %>
  </h3><br />

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago <br />
      <% if @post.user == current_user && user_signed_in? %>
        <%= link_to 'Edit', edit_post_path(@post) %>
        <%= link_to 'Delete', post_path(@post),method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
  </p><br />

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
  
</div>